# -*- coding: utf-8 -*-
"""APSLab_birthday_problem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpqQnCw7ickBORzDLw4fsiA2I5-EHGwk
"""



import matplotlib.pyplot as plt

op_prob = 1.0
n = 20
sample_size = 365
prob_list = []


for i in range(1,n):
  op_prob =  op_prob *(sample_size - (i - 1))/sample_size
  prob_list.append(op_prob)

print(prob_list)

plt.plot(range(1,n),prob_list,".")
plt.show()

import numpy as np
def generate_linear_data(n=100):
  X = np.random.randn(n,2)
  y = (X[:,0]+X[:,1] > 0),astype(int)
  return X,y


def generate_nonlinear_data(n=100,noise = 0.1):
  radius = np.random.rand(n)
  angle = 2* np.pi * np.random.rand(n)

  x1 = radius *np.cos(angle)
  x2 = radius *np.sin(angle)

  X = np.column_stack((x1,x2))
  y = (radius> 0.5).astype(int)

  X+= noise * np.random.randn(n,2)
  return X,y